PlagTracer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('plagtrace.urls')),
    path('admin/', admin.site.urls),
    path('plagiarism-checker/', include('plagtrace.urls', namespace='plagtrace')),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

plagtrace/urls.py
from django.urls import path, re_path
from plagtrace import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = "Plagtrace"

urlpatterns = [
    path('', views.index, name="index"),
    path('plagiarism-checker/', views.index, name="index"),
    path('blog', views.blog, name="blog"),
    path('features', views.features, name="features"),
    path('contact_form', views.contact_form, name='contact_form'),
    path('upload_file', views.upload_file, name='upload_file'),
    path('submitted', views.submitted,name='submitted'),
    path('register', views.UserFormView.as_view(),name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.logout, name='logout')



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plagtrace/models.py
from __future__ import unicode_literals
from django.db import models

class Contact(models.Model):
    username = models.TextField(max_length=200, default= None)
    password = models.CharField(max_length=100 , default=None)
    subject = models.CharField(max_length=500)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.username

class Document(models.Model):
    file1 = models.FileField()
    file2 = models.FileField()

    def __str__(self):
        return self.file1.name + ' ' + self.file2.name

plagtrace/views.py
from django.shortcuts import render, HttpResponseRedirect , HttpResponse, redirect,render_to_response
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic import View
from plagtrace.register_form import UserForm
from plagtrace.file_form import DocumentForm
from plagtrace.form import ContactForm
from django.conf import settings
from .models import Document
from .fyp import plag
from plagtrace.display_form import DisplayForm
import matplotlib.pyplot as plt; plt.rcdefaults()
import numpy as np
import pylab
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
import PIL, PIL.Image
import io
from io import *


def handle_uploaded_file(f):
    with open(settings.MEDIA_ROOT,f, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def upload_file(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            content_file = submitted()
            return render(request, 'plagtrace/document_form.html', {'form':form}, {'content_file':content_file})
    else:
        form = DocumentForm()
    return render(request, 'plagtrace/document_form.html', {'form': form})


def index(request):
    return render(request, 'plagtrace/index.html')


def blog(request):
    return render(request, 'plagtrace/blog.html')


def features(request):
    return render(request, 'plagtrace/features.html')


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            form.save()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('plagtrace:contact_form')

        return render(request,'plagtrace/contact.html',{'form': form, 'errorMessage': 'UserName or Password is incorrect'})
    else:
        form = ContactForm()
        return render(request, 'plagtrace/contact.html', {'form': form})

def submitted():
    obj = Document.objects.values_list('file1').latest('id')
    obj = ' '.join(obj)
    obj1 = Document.objects.values_list('file2').latest('id')
    obj1 = ' '.join(obj1)
    plg = plag(obj, obj1)
    return plg


class UserFormView(View):

    form_class = UserForm
    template_name = 'plagtrace/registration_form.html'
    # display blank form

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
    # process the data

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            # cleaned (normalize) data
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # return User objects if credentials are correct
            user = authenticate(username=username, email=email, password=password)
            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('plagtrace:index')

        return render(request, self.template_name, {'form': form})


def login_user(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('plagtrace:upload_file')
        else:
            print("invalid login details " + username + " " + password)
            return render_to_response('plagtrace/registration/login.html', {}, context)
    else:
        return render(request, 'plagtrace/registration/login.html',{}, context)


@login_required(login_url='/login/')


def Graph_Loader():
    file_content = submitted()
    context =[]
    for content in file_content:
        context.append(content)
    plg = context[0]
    clean = context[1]
    objects = ('plagiarized', 'Clean')
    width = 0.20
    pylab.ylim([0, 100])
    performance = [plg, clean]
    y_pos = np.arange(len(performance))
    performance = [plag, clean]
    plt.bar(y_pos, performance, align='edge', width=width, alpha=0.5)
    plt.xticks(y_pos, objects)
    plt.yticks(range(0, max(performance)))
    plt.title('Plagiarized vs Clean')
    plt.ylabel('Percentage')
    pylab.grid(True)
    return plt.show()
    '''buffer = io.BytesIO()
    canvas = pylab.get_current_fig_manager().canvas
    canvas.draw()
    pil_image = PIL.Image.frombytes("RGB", canvas.get_width_height(), canvas.tostring_rgb())
    pil_image.save(buffer, "PNG")
    pylab.close()
    return buffer.getvalue() '''





'''
def submitted(request):
    if request.method == 'POST':
        form = DisplayForm(request.POST)
        if form.is_valid():
            form.text("hello")
        return HttpResponseRedirect('submitted')
    else:
        form = DisplayForm()
    return render(request, 'plagtrace/document_form.html', {'form': form})





            for field in request.FILES.keys():
                for form_file in request.FILES.getlist(field):
                    save_uploaded_file_to_media_root(form_file)



def save_uploaded_file_to_media_root(f):
    with open('%s%s' % (settings.MEDIA_ROOT, f.name), 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


'''

plagtrace/templates/plagtrace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PlagirismTracer</title>
    <!--load the path of static files -->
     {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'plagtrace/css/bootstrap.css'%} " rel="stylesheet">

    <!-- Material Design Bootstrap -->
    <link href="{% static 'plagtrace/css/mdb.min.css' %}" rel="stylesheet">

    <!-- Your custom styles (optional) -->
    <link href="{% static 'plagtrace/css/style.css' %}" rel="stylesheet">


    <!-- Font Awesome -->
    <link href="{% static 'plagtrace/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'plagtrace/js/map.js' %}"></script>
</head>
<body>
    <header class="mb-lg-5">

		<!-- Sidebar navigation -->
			<div id="slide-out" class="side-nav fixed purple darken-4">
			<ul class="custom-scrollbar">
			    <!-- Logo -->
			    <li>
			        <div class="logo-wrapper waves-light">
			            <a href="{% url 'plagtrace:index' %}"><img src="{% static 'plagtrace/images/lll.png' %}" class="img-fluid flex-center"></a>
			        </div>
			    </li>
			    <!--/. Logo -->
			    <!--Social-->
			    <li>
			        <ul class="social">
			            <li><a href="#" class="icons-sm fb-ic"><i class="fa fa-facebook"> </i></a></li>
			            <li><a href="#" class="icons-sm pin-ic"><i class="fa fa-pinterest"> </i></a></li>
			            <li><a href="#" class="icons-sm gplus-ic"><i class="fa fa-google-plus"> </i></a></li>
			            <li><a href="#" class="icons-sm tw-ic"><i class="fa fa-twitter"> </i></a></li>
			        </ul>
			    </li>
			    <!--/Social-->
			    <!--Search Form-->
			    <li>
			        <form class="search-form" role="search">
			            <div class="form-group md-form mt-0 pt-1 waves-light">
			                <input type="text" class="form-control" placeholder="Search">
			            </div>
			        </form>
			    </li>
			    <!--/.Search Form-->
			    <!-- Side navigation links -->
			    <li>
			        <ul class="collapsible collapsible-accordion">
			            <li><a class="collapsible-header waves-effect arrow-r"><i class="fa fa-home mr-3"></i>Home<i class="fa fa-angle-down rotate-icon"></i></a>
			                <div class="collapsible-body">
			                    <ul>
			                        <li><a href="{% url 'plagtrace:index' %}" class="waves-effect">Start</a>
			                        </li>

			                    </ul>
			                </div>
			            </li>
			            <li><a class="collapsible-header waves-effect arrow-r"><i class="fa fa-hand-pointer-o"></i>Features<i class="fa fa-angle-down rotate-icon"></i></a>
			                <div class="collapsible-body">
			                    <ul>
			                        <li><a href="{% url 'plagtrace:upload_file' %}" class="waves-effect">one to one comparison</a>
                                    </li>
                                    <li><a href="{% url 'plagtrace:features' %}" class="waves-effect">why PlagTracer</a>
                                    </li>
			                    </ul>
			                </div>
			            </li>
			            <li><a class="collapsible-header waves-effect arrow-r"><i class="fa fa-eye"></i> About<i class="fa fa-angle-down rotate-icon"></i></a>
			                <div class="collapsible-body">
			                    <ul>
			                        <li><a href="{% url 'plagtrace:blog' %}" class="waves-effect">Blog</a>
			                        </li>
			                    </ul>
			                </div>
			            </li>
			            <li><a class="collapsible-header waves-effect arrow-r"><i class="fa fa-envelope-o"></i> Contact me<i class="fa fa-angle-down rotate-icon"></i></a>
			                <div class="collapsible-body">
			                    <ul>
			                        <li><a href="{% url 'plagtrace:contact_form' %}" class="waves-effect">Contact Us</a>
                                    </li>
                                </ul>

			                </div>
			            </li>
			        </ul>
			    </li>
			    <!--/. Side navigation links -->
			</ul>
				<div class="sidenav-bg mask-strong"></div>
			</div>
			<!--/. Sidebar navigation -->

			        <!-- Navbar -->
	        <nav class="navbar fixed-top deep-purple lighten-1 navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav ">
	            <!-- SideNav slide-out button -->
	            <div class="float-left">
	                <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars"></i></a>
	            </div>
	            <!-- Breadcrumb-->
	            <div class="breadcrumb-dn mr-auto">
	                <p>PlagTracer</p>
	            </div>
	            <ul class="nav navbar-nav nav-flex-icons ml-auto">
	                <li class="nav-item">
	                    <a href="{% url 'plagtrace:contact_form' %}" class="nav-link"><i class="fa fa-envelope"></i> <span class="clearfix d-none d-sm-inline-block">Contact</span></a>
	                </li>
	                <li class="nav-item">
	                    <a href="{% url 'plagtrace:features' %}" class="nav-link"><i class="fa fa-comments-o"></i> <span class="clearfix d-none d-sm-inline-block">Support</span></a>
	                </li>
                    <li class="nav-item">
	                    <a href="{% url 'plagtrace:register' %}" class="nav-link"><i class="fa fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Signup</span></a>
	                </li>
	            </ul>
	        </nav>
	        <!-- /.Navbar -->
    </header>

    <main class="container mt-5">
        {% block body %}




        {% endblock %}
    </main>
    		<!--Footer-->
		<footer class="page-footer font-small deep-purple pt-4 mt-4">

		    <!--Footer Links-->
		    <div class="container text-center text-md-left">
		        <div class="row">

		            <!--First column-->
		            <div class="col-md-6">
		                <h5 class="text-uppercase">PlagTracer</h5>
		                <p>Work With US And Never Compromise on Quality.</p>
		            </div>
		            <!--/.First column-->
		            <div class="col-md-3 ml-auto">

		                <h6 class="text-uppercase font-weight-bold">
		                    <strong>About</strong>
		                </h6>
		                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
		                <ul class="list-unstyled">
		                    <p>
		                        <a href="{% url 'plagtrace:features' %}">WHY WE CHOOSE IT</a>
		                    </p>
		                    <p>
		                        <a href="{% url 'plagtrace:index' %}">PLAGTRACER</a>
		                    </p>
		                    <p>
		                        <a href="{% url 'plagtrace:blog' %}">BLOG</a>
		                    </p>
		                    <p>
		                        <a href="{% url 'plagtrace:contact_form' %}">CONTACT US</a>
		                    </p>
		                </ul>
		            </div>

		            <!--Second column-->
		            <div class="col-md-3">
		                <h6 class="text-uppercase font-weight-bold">
		                    <strong>Contact</strong>
		                </h6>
		                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
		                <p>
		                    <i class="fa fa-home mr-3"></i> Mandi Bahauddin, UOS</p>
		                <p>
		                    <i class="fa fa-envelope mr-3"></i> PlagTracer@gmail.com</p>
		                <p>
		                    <i class="fa fa-phone mr-3"></i> + 0340 1602170</p>
		                <p>
		                    <i class="fa fa-print mr-3"></i> + 0546 9922175</p>
		            </div>
		            <!--/.Second column-->
		        </div>
		    </div>
		    <!--/.Footer Links-->
		    <hr>
            <!--Call to action-->
		    <div class="text-center py-3">
		        <ul class="list-unstyled list-inline mb-0">
		            <li class="list-inline-item">
		                <h5 class="mb-1">Register for free</h5>
		            </li>
		            <li class="list-inline-item">
		                <a href="{% url 'plagtrace:register' %}" class="btn btn purple-gradient" style="border-radius: 20px; ">Sign up!</a>
		            </li>
		        </ul>
		    </div>
		    <!--/.Call to action-->

		    <hr>
 <!--Social buttons-->
             <div class="text-center">
                  <ul class="list-unstyled list-inline">
                      <li class="list-inline-item"><a href="https:\\www.facebook.com" class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-facebook"></i></a></li>
                      <li class="list-inline-item"><a href="https:\\www.twitter.com" class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-twitter"></i></a></li>
                      <li class="list-inline-item"><a href="https:\\www.google.com" class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-google-plus"></i></a></li>
                      <li class="list-inline-item"><a href="https:\\www.linkedin.com" class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-linkedin"></i></a></li>
                   </ul>
              </div>
                      <!--/.Social buttons-->

		    <!--Copyright-->
		    <div class="footer-copyright py-3 text-center">
		        © 2018 Copyright:
		        <a href="https://mdbootstrap.com/material-design-for-bootstrap/"> PlagTracer.com </a>
		    </div>
		    <!--/.Copyright-->

		</footer>
		<!--/.Footer-->

<!-- Scripts -->
<!-- JQuery -->

        <script type="text/javascript" src="{% static 'plagtrace/js/jquery-3.2.1.min.js' %}"></script>

		<!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="{% static 'plagtrace/js/bootstrap.min.js' %}"></script>
		<!-- Bootstrap tooltips -->
        <script type="text/javascript" src="{% static 'plagtrace/js/popper.min.js' %}"></script>

		<!-- MDB core JavaScript -->

		<script type="text/javascript" src="{% static 'plagtrace/js/mdb.min.js' %}"></script>
        <script type="text/javascript">

			// SideNav Button Initialization
			// language=JQuery-CSS
            $(".button-collapse").sideNav(
				{
					edge: 'left', // Choose the horizontal origin
					closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
					});
			// SideNav Scrollbar Initialization
			var sideNavScrollbar = document.querySelector('.custom-scrollbar');
			Ps.initialize(sideNavScrollbar);

		</script>

</body>
</html>

plagtrace/templates/plagtrace/blog.html
{% extends 'plagtrace/base.html' %}
{% load staticfiles %}


{% block body %}
<main class="container">
<section class="pt-5 mt-4 pb-3">

    <!--Grid row-->
    <div class="row">
        <div class="col-md-12">
            <!--Featured image-->
            <div class="card card-cascade wider reverse">
                <div class="view overlay">
                    <img src="{% static 'plagtrace/images/Plagiarism.png'  %}" alt="Wide sample post image" class="img-fluid ml-5">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <!--Post data-->
                <div class="card-body text-center">
                    <h2>
                        <a class="font-weight-bold">Recent News.</a>
                    </h2>
                    <p>Written by
                        <a>Sadia Parveen</a>, 20/04/2018</p>

                    <!--Social shares-->
                    <div class="social-counters ">

                        <!--Facebook-->
                        <a class="btn btn-fb ">
                            <i class="fa fa-facebook left "></i>
                            <span class="clearfix d-none d-md-inline-block">Facebook</span>
                        </a>
                        <span class="counter ">46</span>

                        <!--Twitter-->
                        <a class="btn btn-tw ">
                            <i class="fa fa-twitter left "></i>
                            <span class="clearfix d-none d-md-inline-block">Twitter</span>
                        </a>
                        <span class="counter ">22</span>

                        <!--Google+-->
                        <a class="btn btn-gplus ">
                            <i class="fa fa-google-plus left "></i>
                            <span class="clearfix d-none d-md-inline-block">Google+</span>
                        </a>
                        <span class="counter ">31</span>

                        <!--Comments-->
                        <a class="btn btn-default ">
                            <i class="fa fa-comments-o left "></i>
                            <span class="clearfix d-none d-md-inline-block">Comments</span>
                        </a>
                        <span class="counter ">18</span>

                    </div>
                    <!--Social shares-->

                </div>
                <!--Post data-->
            </div>

            <!--Excerpt-->
            <div class="excerpt mt-5">
                <p>Students can benefit from our plagiarism detection software by having their essays
                    or assignments papers checked for any plagiarism. Many college and university students
                    face extreme penalties for plagiarism such as failing an assignment, loss of privileges,
                    academic probation, or even expulsion. In some cases, punishments can include lawsuits,
                    criminal charges, and even imprisonment. Even if you commit unintentional plagiarism,
                    it can still be viewed as plagiarism in the eyes of the law.
                    Why risk being penalized for plagiarism when with PlagTracer.com you can be 100%
                    sure that your writing is unique?
                </p>

                <p>PlagTracker reviewed by faculty of University of Sargodha Mandi Bahauddin Campus.
                    Simply upload your file with supported extension like txt, docx, pptx, xlsx etc click on the button to upload.
                    The software allowing you to scan lengthy essays –
                    if your Assignment is longer, simply it will take more time  to scan then you have to be patience for it.</p>
            </div>
        </div>
    </div>


</section>
</main>
{% endblock %}

plagtrace/templates/plagtrace/contact.html
{% extends 'plagtrace/base.html' %}


{% block body %}

<main class="container">
    <!--Section: Contact v.1-->
    <section class="py-3">

			    <!--Section heading-->
			    <h2 class="font-weight-bold text-center h1 py-5">Contact us</h2>
			    <!--Section description-->
			    <p class="text-center mb-5 pb-4">In Case of any query or feed back you can contact us.</p>

			    <div class="row">

			        <!--Grid column-->
			        <div class="col-lg-5 mb-4">

			            <!--Form with header-->
			            <div class="card">

			                <div class="card-body">
			                    <!--Header-->
			                    <div class="form-header purple-gradient">
			                        <h3>
			                            <i class="fa fa-envelope"></i> Write to us:</h3>
			                    </div>

			                    <p>Your feedback really matter.</p>
			                    <br>

			                    <!--Body-->
                                <form method="post" action="{% url 'plagtrace:contact_form' %}">
                                    {% csrf_token %}
                                    {% if errorMessage %}
                                        <p><strong class="text-danger">{{ errorMessage }}</strong></p>
                                    {% endif %}

                                    <div class="md-form">
                                        <i class="fa fa-user prefix grey-text"></i>
                                        {{form.username }}
                                        <label for="form-name" id="id_username">Your name</label>
                                    </div>

                                    <div class="md-form">
                                        <i class="fa fa-envelope prefix grey-text"></i>
                                        {{form.password}}
                                        <label for="form-email" id="id_password">Your Password</label>
                                    </div>

                                    <div class="md-form">
                                        <i class="fa fa-tag prefix grey-text"></i>
                                        {{form.subject }}
                                        <label for="form-Subject">Subject</label>
                                    </div>

                                    <div class="md-form">
                                        <i class="fa fa-pencil prefix grey-text"></i>
                                        {{form.description }}
                                        <label for="form-text">Detail Description</label>
                                    </div>
                                    <div class="text-center">
                                        <button class="btn purple-gradient" type="submit"><i class="fa fa-user mr-2"></i>Submit</button>
                                    </div>
                                </form>

			                </div>

			            </div>
			            <!--Form with header-->

			        </div>
			        <!--Grid column-->

			        <!--Grid column-->
			        <div class="col-lg-7">

			            		            <!--Buttons-->
			            <div class="text-center">
			                    <a class="btn-floating purple-gradient">
			                        <i class="fa fa-map-marker "></i>
			                    </a>
			                    <p>Punjab, UOS M.B.Din</p>
			                    <p>Pakistan</p>

			                    <a class="btn-floating purple-gradient">
			                        <i class="fa fa-phone"></i>
			                    </a>
			                    <p>+92 3401602170</p>
			                    <p>Mon - Fri, 8:00-22:00</p>

			                    <a class="btn btn-floating purple-gradient">
			                        <i class="fa fa-envelope"></i>
			                    </a>
			                    <p>PlagTrace@gmail.com</p>
			                    <p>PlagInfo@gmail.com</p>
			            </div>

			        </div>
			        <!--Grid column-->

			    </div>

    </section>
    <!--Section: Contact v.1-->



</main>

{% endblock %}

plagtrace/templates/plagtrace/document_form.html
{% extends 'plagtrace/base.html' %}
{% block body %}
    <main class="container ">
        <h3><span class="badge purple-gradient mt-5">One to One comparison</span></h3>
			<div class="row">

                {% for content in content_file %}
				<div class="col-md-6">
                    {{content}}
                </div>
                {% endfor %}

			</div>
        <form action="{% url 'plagtrace:upload_file' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
			<div class="row">
				<div class="col-md-6">
                    <div class="md-form mt-4">
                        <div class="file-field">
                            <div class="btn btn-secondary btn-sm float-left">
                                <span>Upload file</span>
                                {{ form.file1}}
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload your file">
                            </div>
                        </div>
                    </div>
                </div>
				<div class="col-md-6">
                        <div class="md-form mt-4">
                            <div class="file-field">
                                <div class="btn btn-secondary btn-sm float-left">
                                    <span>Upload file</span>
                                    {{ form.file2}}
                                </div>
                                <div class="file-path-wrapper">
                                    <input class="file-path validate" type="text" placeholder="Upload your file">
					            </div>
                            </div>
                        </div>
                    <button class="btn btn-outline-deep-purple btn-rounded waves-effect mt-5"><i class="fa fa-magic mr-1" type="submit"></i> Analyze</button>
				</div>

			</div>
        </form>
    </main>
{% endblock %}

plagtrace/templates/plagtrace/form-template.html
{% for field in form %}
    <div class = 'form-group'>
        <div class="col-sm-offset-2 col-sm-10">
            <span class = "text-danger small">{{ field.errors }}</span>
        </div>

        <label  class="control-label col-sm-2" for="materialFormRegisterNameEx">{{ field.label_tag }}</label>

    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

plagtrace/templates/plagtrace/index.html
{% extends 'plagtrace/base.html' %}

{% load staticfiles %}


{% block body %}

    <div class="container">

	        <!--Grid row-->
        <div class="row pt-lg-5">

            <div class="col-md-7 ">
                <div class="view overlay z-depth-1-half ">
                    <img src="{% static 'plagtrace/images/pic.jpg' %}" class="img-fluid " alt="">
                    <div class="mask flex-center rgba-purple-light">
                        <p class="white-text">PlagTracer</p>
                    </div>
                </div>
            </div>
            <div class="col-md-5 ">
                <h2>Plagiarism Tracer</h2>
                <hr>
                <p >
                    PlagTracer is the first free, open source tool with valuable functionality.It provides advance functionality like semantics instead of keyword based matching.
                    it makes comparison between 2 documents and detect the plagiarism. Lets get started
                </p>
                <a href="{% url 'plagtrace:upload_file' %}" class="btn btn purple-gradient">GET STARTED</a>


            </div>
        </div>
        <!--Section: Testimonials v.2-->
        <section class="text-center pb-5">
            <!--Section heading-->
            <h1 class="font-weight-bold h1 py-5">Founder</h1>
            <!--Section description-->
            <div class="testimonial">
                        <!--Avatar-->
                        <div class="avatar mx-auto">
                            <img src="{% static 'plagtrace/images/sadia.png' %}" class="rounded-circle img-fluid" alt="Author Image">
                        </div>
                        <!--Content-->
                        <p>
                            <i class="fa fa-quote-left"></i>
                            I'm the founder of this website.python ,Bootstrap, NLP involves in this project.
                            </p>

                        <h4>Sadia Parveen</h4>
                        <h6>Studied at UOS M.B.Din</h6>

                        <!--Review-->
                        <i class="fa fa-star blue-text"> </i>
                        <i class="fa fa-star blue-text"> </i>
                        <i class="fa fa-star blue-text"> </i>
                        <i class="fa fa-star blue-text"> </i>
                        <i class="fa fa-star-half-full blue-text"> </i>
            </div>
        </section>
    </div>

{% endblock %}